/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package grpckotlin.simple

import io.grpc.stub.StreamObserver

class GisMappingServiceImpl : GisMappingServiceGrpc.GisMappingServiceImplBase() {

    override fun translateEnToFr(request: Request?, responseObserver: StreamObserver<Response>?) {

        val reply = Response.newBuilder().setFrMessage("en Francais est 'moi?'").build()
        responseObserver?.onNext(reply)
        responseObserver?.onCompleted()
    }
}

